apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: db
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongo
  namespace: db
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo
  namespace: db
subjects:
  - kind: ServiceAccount
    name: mongo # Name is case sensitive
    namespace: db
roleRef:
  kind: Role
  name: mongo
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      serviceAccountName: mongo
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pass
        image: mongo:4.4
        imagePullPolicy: IfNotPresent
        name: mongo
        args: 
        - "mongod"
        - "--replSet"
        - "rs0"
        - "--bind_ip"
        - "0.0.0.0"
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: "app=mongo"
        - name: KUBE_NAMESPACE
          value: "db"
        - name: MONGODB_USERNAME
          value: "user"
        - name: MONGODB_PASSWORD
          value: "pass"
        - name: MONGODB_DATABASE
          value: "admin"
        - name: MONGO_PORT
          value: "27017"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: db
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  sessionAffinity: None
  type: ClusterIP
